version: '3'
services:
  database:
    image: mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
  redis:
    image: redis
    restart: unless-stopped
  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbit:/var/lib/rabbitmq
  backend:
    image: ghcr.io/regenbogen-ice/backend:canary
    restart: unless-stopped
    depends_on:
      - database
      - redis
      - rabbit
    env_file:
      - .env
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_URL: redis://redis
      RABBIT_URL: ${RABBIT_URL}
      TZ: Europe/Berlin
  api:
    image: ghcr.io/regenbogen-ice/api:canary
    restart: unless-stopped
    depends_on:
      - database
      - redis
      - rabbit
      - backend
    env_file:
      - .env
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_URL: redis://redis
      RABBIT_URL: ${RABBIT_URL}
      TZ: Europe/Berlin
  
  frontend:
    image: ghcr.io/regenbogen-ice/frontend:canary
    restart: unless-stopped
    depends_on:
      - api
      - backend


volumes:
  db:
  rabbit:
